### ISSUE TITLE
New Error: "XResolution: Rational with zero denominator (num = 1000000)."

### ISSUE THREAD

**Issue by MSLDgit** [nci/drishti#67]
Hi Ajay,
I am facing an error since today (although I think I did not change anything):
When importing a directory of grayscale tiff images an error window appears for every image imported:
"XResolution: Rational with zero denominator (num = 1000000)."
This error pops up now with every dataset I tested so far and also with a dataset I could actually import today in the morning without problems.
I used 2.7 for this. I tried to use a version freshly unzipped from the directory and then also tried with the new 3.0 version. There the same error appears. 
Many thanks for any help!
Best
Miles

**Comment by MSLDgit** [comment]
Ok nevermind, solved it my self.
was importing the images 1 per 1 and not the directory...

**Comment by MSLDgit** [comment]
ok, sorry for the confusion. The issue still persists and seems to be with later versions of drishti import: With version 2.6.4 and 2.6.5 I can still import a directory of certain tif files, with version 2.7 and 3.0 this is not possible.
However, I have another dataset (also directory of tif files) which can be imported with 2.7 and 3.0 (and 2.6.4 and 2.6.5). Right now I do not know the difference of these files...
My workaround is now to use old versions for import of these files.

**Comment by AjayLimaye** [comment]
Can you send me a small sample that causes this error.  I will try to
figure out what might be causing it.
Cheers,
Ajay

**Comment by MSLDgit** [comment]
Yes, sure. How can I do this?
Best
Miles

**Comment by AjayLimaye** [comment]
Cloudstore should work if you are in university environment.

**Comment by MSLDgit** [comment]
Hi, 
1. recon_sample.zip (19,9 MB) [application/zip]
https://webmail.server.uni-frankfurt.de/imp/attachment.php?id=6249adb3-1b20-477f-b0bb-4b518d021656&u=s7493063
hope that works

**Comment by AjayLimaye** [comment]
Please replace tiffplugin.dll in importplugins directory with the one from
here
https://cloudstor.aarnet.edu.au/plus/s/ykqMmmikfXxHxKC

Cheers,
Ajay

**Comment by AjayLimaye** [comment]
Yes, would only work in v3.0 - somethings have changed from v2.7 to v3.0.
