### ISSUE TITLE
README citation includes wrong doi

### ISSUE THREAD

**Issue by StephenCatsamas** [nci/drishti#73]
The readme has the citation

Hu Yuzhi, Limaye Ajay and Lu Jing. 2020 Three-dimensional segmentation of computed tomography data using Drishti Paint:new tools and developments. R.Soc.open sci. 7:201033. doi: http://doi.org/10.1098/rsos.202033

which has incorrect doi: http://doi.org/10.1098/rsos.202033
The correct doi is: https://doi.org/10.1098/rsos.201033

**Comment by AjayLimaye** [comment]
Thanks,
Ajay
