### ISSUE TITLE
multiple volumes loading crashes in highres mode

### ISSUE THREAD

**Issue by drishtiuser12** [nci/drishti#74]
Hi Ajay Limaye, 
I am trying to open 2 Volumes at once. But drishti 2.7-3.2 crashes when changing to Highres mode. Weirdly it works when trying with drishti 2.4. The files are quite big but theoretically should be possible. Both volumes are 4.2 GB with aprox 2000x2000x1200 in size. 
I have a NVIDIA  RTX4070Ti with 12 GB GPU memory, and 64GB RAM. 
I set the nvidia preferences to OPENGL use NVIDIA graphics card. In drishti my texture memory size is set to 11GB and max drag volume size to 128mb. 
Any suggestions what i could change? 
THank you for your help

Btw. thank you for that great program I am using for some years now!

**Comment by AjayLimaye** [comment]
Fixed the bug and the binary releases have been updated.
Thanks.
Ajay
