### ISSUE TITLE
Unable to open the application

### ISSUE THREAD

**Issue by Zafar2alig** [nci/drishti#76]
@AjayLimaye 
I'm facing trouble in opening the Drishti v3.2.27.10.23. It says "The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem." and then it says "The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem." 
This is happening after I formatted the laptop. Earlier the issue was different. Whenever I tried to extract the tagged region from DrishtiPaint, the app crashed and everything vanished. 
Please help me in this regard. 
Thanks,
Shahnawaz

**Comment by AjayLimaye** [comment]
Hi Shahnawaz,
  Usually these dlls are installed with the Operating System updates.
Anyways here they are AdditionalDlls
<https://anu365-my.sharepoint.com/:f:/g/personal/u9707062_anu_edu_au/EvXdyy_tpRxNrS8K4NeBtKkBd5TE_vW7JanTM-ZtqUu8Gw?e=DvhfRv>
Cheers,
Ajay

**Comment by Zafar2alig** [comment]
Hi Ajay,
Can you help me to reset the "Texture Memory Size"? It just asks once after installing the program, if i want to change the same, how to do?

Thanks,
Shahnawaz

**Comment by AjayLimaye** [comment]
This is the size of memory on your GPU.

**Comment by Zafar2alig** [comment]
So, my laptop is showing GPU memory 15.8Gb, then should I set "Texture Memory Size" to 16.0Gb? Or any alternative.

**Comment by AjayLimaye** [comment]
yes, should be fine.
what card do you have on the laptop?

**Comment by Zafar2alig** [comment]
Intel(R) Iris(R) Xe Graphics

**Comment by AjayLimaye** [comment]
Intel Iris Xe does not have its own memory, it uses the main CPU memory.
Hence you would not be able to do fast rendering for large volumes.
Cheers,
Ajay

**Comment by Zafar2alig** [comment]
What about NVIDIA 310 and NVIDIA GeForce MX330? Can you suggest me some ideal graphic cards to run the software? I've tiff files of 2Gb size and their respective .pvl.nc.001 files of 1Gb size for 3D micro CT scan of lizard skull. Please help me, I've to do the analysis in an urgent time.
I'm attaching the graphics details for whatever systems I've with me.
For desktop:
![Screenshot (1)](https://github.com/nci/drishti/assets/156498873/9bbf30af-9444-4cbe-bbb3-eb90563656ec)
![Screenshot (2)](https://github.com/nci/drishti/assets/156498873/effd9405-325b-4243-8b0b-7e25d2d16864)

For laptop having Intel Iris Xe graphics:
![Screenshot (1)](https://github.com/nci/drishti/assets/156498873/de7a96bb-d2a7-4fda-99f4-d1667d328c65)

For laptop having Intel Iris Xe and NVIDIA GeForce MX330 graphics:
![image](https://github.com/nci/drishti/assets/156498873/ff75e0cf-ec45-48f1-823e-4e0fb40bbbcf)
![Screenshot (3814)](https://github.com/nci/drishti/assets/156498873/d4b0cb9b-e9b8-4bc2-b10b-9bd76b46c5d9)

**Comment by AjayLimaye** [comment]
GeForce 310/330s or Iris Xe cards would be very very sluggish when handling
1GB data sets, because they just do not have the required memory capacity
(shared memory is slow when it comes to rendering) as well as the compute
speed.
One option is to subsample the data to see what would work on your machine.
Cheers,
Ajay

**Comment by Zafar2alig** [comment]
Please suggest me the graphics card that can handle this much big data. I don't want to subsample, I have to work on whole data at once.

**Comment by AjayLimaye** [comment]
Graphics cards with 4GB dedicated memory and above would work fine (more
the merrier).

**Comment by Zafar2alig** [comment]
Hi Ajay, 
Now I have installed Graphics card with 4GB dedicated memory, but while working on the program it responds little late. When I zoom in/out or move the rendered 3D image, it takes some time for the same. Please help fix the issue. 

Thanks

**Comment by AjayLimaye** [comment]
Hi  Shahnawaz,
  Just make sure that the program is running on your dedicated
graphics card.
What is the gpu you are using ?
Cheers,
Ajay

**Comment by Zafar2alig** [comment]
GPU in use is Intel(R) Graphics 630

**Comment by AjayLimaye** [comment]
I believe Intel 630 does not have dedicated texture memory, it is all
system shared.
The program will run very slow for the size of datasets you have.

**Comment by Zafar2alig** [comment]
That's why we installed NVIDIA GeForce GT 730, still running slow

**Comment by AjayLimaye** [comment]
Yes, because this is a very very low end card.

**Comment by Zafar2alig** [comment]
Please suggest me a card that can work for me. I want to finish my work asap. It's been more than a month I'm trying to fix the problems.

**Comment by AjayLimaye** [comment]
Depends how much funds you have to spare.  Also need to make sure that you
have adequate power supply for your machine.
nvidia geforce gtx 1080 should do the work.

**Comment by Zafar2alig** [comment]
Seems impossible to install gtx 1080 in my system, the technician said:
"1.  GTX 1080 is EOL and not available.
2.  It will not fit into the DELL Desktop cabinet at your office
3.  The Dell Desktop SMPS does not have the required PCI-express 6 pin and 8 pin power connector required to power the GTX 1080 graphics card
4.  It is not possible to change teh SMPS in the Dell Desktop because the Dell motherboards are customized and the motherboards power connector is incompatible with the standard SMPS available in the market"

**Comment by Zafar2alig** [comment]
I tried to install drishti on ubuntu systems but failed to do so. The error was something like:
/drishti: /lib/x86-64-Linux-gnu/libc.so.6: version GLIBC 2.34 not found (required by ./drishti)

/drishtt:/lib/x86-64-linux-gnu/libstdc++.so.6: version GLIBCXX 3.4.29 not found (required by /opt/Drishti/Drishti-3.2/sharedltbs/1tbQGLViewer-qts.so.2)

/drishtt:/lib/x86 64-Linux-gnu/libstdc++.so.6: version GLIBCXX 3.4.29 not found (required by /opt/Drishti/Drishti-3.2/sharedlibs/Ltbassimp.so.5)

/drishti: /lib/x86-64-Linux-gnu/libstdc++.so.6: version CXXABI 1.3.13 not found (required by /op/Drishtl/Drishti-3.2/sharedllbs/Libassimp.so.5)

/drishtt:/lib/x86 64-Linux-gnu/libc.so.6: version GLIBC 2.32' not found (required by /opt/Drishtl/Drishti 3.2/sharedlibs/ltbass Emp.so.5)

/drishti: /lib/x86 64-1Unux-gnu/Libc.so.6: version GLIBC 2.33' not found (required by /opt/Drishtl/Drishti-3.2/sharedlibs/libasstmp.so.5)

**Comment by Zafar2alig** [comment]
If nothing works please suggest an alternative to drishti where I can landmark my 3D images, as effective and easily as here. 

Thanks

**Comment by AjayLimaye** [comment]
https://medvis.org/software/
https://www.theobjects.com/dragonfly/index.html

**Comment by Zafar2alig** [comment]
Thanks for your continuous support
