### ISSUE TITLE
Drishti render and Drishti paint crashing 

### ISSUE THREAD

**Issue by Zafar2alig** [nci/drishti#77]
I'm using the latest version of Drishti and facing trouble since several weeks. Drishti Paint crashes on my laptop whenever I try to extract tagged region, while Drishti renderer crashes on my desktop when I upload some .pvl.nc file to work on it. Laptop is having Intel(R) Iris(R) Xe Graphics card and the desktop has two graphics cards: (1) Intel (R) HD Graphics 360 and (2) NVIDIA 310
Urgent help needed. 

Thanks.

**Comment by AjayLimaye** [comment]
What sized volumes are you trying out and what size is the memory on your
machine.
Cheers,
Ajay

**Comment by Zafar2alig** [comment]
I've 0.8 to 1.0 Gb sized .pvl.nc.001 sized volumes. Laptop is having 15.8Gb GPU memory, desktop has 15.9Gb GPU memory for both graphic cards separately.

**Comment by AjayLimaye** [comment]
The memory you have mentioned is the shared memory - very slow when it
comes to rendering the datasets you have.
NVIDIA GPUs have dedicated texture memory 1GB (NV 310) and 2GB (MX 330),
but these are not really fast processors, so the rendering will be very
slow.
Make sure that the program is running in this dedicated graphics card via
NVIDIA control panel.
[image: image.png]


Also try subsampling your data.
Cheers,
Ajay
