### ISSUE TITLE
Drishti import missing slices upon completion 

### ISSUE THREAD

**Issue by toconquer** [nci/drishti#78]
Hello! 
We have a Windows GPU workstation running Drishti Import. The workstation pulls files in from a Windows File Server over 10 gigabit networking. Once completed, the resulting image is missing slices. Do you have guidance on generating log data that could help us figure out why this is occurring? I'm a sysadmin and can provide needed information. Thank you!

**Comment by AjayLimaye** [comment]
By missing slices, do you mean no data is written or only some slices are
missing ?
Cheers,
Ajay

**Comment by toconquer** [comment]
A model is viewable but some slices are missing. If we run the Import from a local disk, it's fine. If we run it with the files on a network share multiple times, slices are missing after completion, and the missing slices will be different if we run it more than once.

**Comment by AjayLimaye** [comment]
What is the format of the file being imported?

**Comment by toconquer** [comment]
We are importing .bmp stacks (generated by the reconstruction software,
NRecon.) These are being imported to the .pvl.nc format that is read by
Drishti.

**Comment by toconquer** [comment]
This is being closed. Microsoft antivirus was interrupting the import and when files were locked, Drishti would skip that slice.

**Comment by AjayLimaye** [comment]
There is nothing in the code that might give rise to this behaviour -
essentially some slices not being read properly in order for import.
Is it possible that the server might be playing up when reading lots of
small files.
Cheers,
Ajay

**Comment by toconquer** [comment]
Microsoft antivirus was locking the files on the client to scan them. When
a file is locked, that file is skipped along with its slice.
